@echo off
@title radegast_install
echo radegast_install
echo ================================
echo.
set PYTHON_VERSION=3.14
set APP_DIR=%LOCALAPPDATA%\winpython-oneclick
set PYTHON_DIR=%APP_DIR%\python
set PYTHON_EXE=%PYTHON_DIR%\python.exe
set PYTHONW_EXE=%PYTHON_DIR%\pythonw.exe
set SCRIPTS_DIR=%PYTHON_DIR%\Scripts
set PYTHON_ZIP=%TEMP%\winpython_3_13.zip
set INSTALL_SCRIPT=%TEMP%\install_inline.py
set INSTALL_B64=%TEMP%\install_inline.b64
echo.

if exist "%PYTHON_EXE%" (
    echo Python already installed at %PYTHON_DIR%
    goto :install_uv
)

echo.
echo Downloading portable Python...
powershell -Command "[Net.ServicePointManager]::SecurityProtocol = [Net.SecurityProtocolType]::Tls12; Invoke-WebRequest -Uri 'https://cdn.adamhlavacek.com/winpython_3_13.zip' -OutFile $env:PYTHON_ZIP"
if errorlevel 1 (
    echo ERROR: Failed to download Python
    PAUSE
    exit /b 1
)
echo Download complete.
echo.
echo Extracting Python to %APP_DIR%...
if not exist "%APP_DIR%" mkdir "%APP_DIR%"
powershell -Command "Expand-Archive -Path $env:PYTHON_ZIP -DestinationPath $env:APP_DIR -Force"
if errorlevel 1 (
    echo ERROR: Failed to extract Python
    PAUSE
    exit /b 1
)
del "%PYTHON_ZIP%"
echo Python extracted successfully.
echo.
if not exist "%PYTHON_EXE%" (
    echo ERROR: Python executable not found at %PYTHON_EXE%
    PAUSE
    exit /b 1
)
echo.

:install_uv
echo Checking for uv...
set "UV_EXE=%SCRIPTS_DIR%\uv.exe"

rem 1. Install uv via pip if not found
if not exist "%UV_EXE%" (
    echo Installing uv via pip...
    "%PYTHON_EXE%" -m pip install uv
    if errorlevel 1 (
        echo ERROR: Failed to install uv
        PAUSE
        exit /b 1
    )
) else (
    echo uv is already installed.
)

rem 2. Add to Current Process PATH (So we can use it immediately below)
echo.
echo Configuring environment variables...
set "PATH=%SCRIPTS_DIR%;%PATH%"

rem 3. Add to Persistent User PATH (Safely using PowerShell to avoid duplicates)
powershell -Command "$targetPath = '%SCRIPTS_DIR%'; $currentPath = [Environment]::GetEnvironmentVariable('Path', 'User'); if ($currentPath -notlike '*' + $targetPath + '*') { [Environment]::SetEnvironmentVariable('Path', $currentPath + ';' + $targetPath, 'User'); Write-Host 'Added to User PATH.' } else { Write-Host 'Already in User PATH.' }"

:install_app
echo.
echo Writing installation script...
if exist "%INSTALL_B64%" del "%INSTALL_B64%"
if exist "%INSTALL_SCRIPT%" del "%INSTALL_SCRIPT%"
set SB=%INSTALL_B64%
set SO=%INSTALL_SCRIPT%
echo|set /p="IiIiCmluc3RhbGxfcmFkZWdhc3QucHkKPT09PT09PT09PT09PT09PT09PQpSZWdpc3RlcnMgdGhpcyBtYWNoaW5lIGFzIGEgUmFkZWdhc3QgZGV2aWNlIGFuZCBydW5zIHRoZSBwbGF0Zm9ybS1zcGVjaWZpYwppbnN0YWxsIHNjcmlwdCBkZWxpdmVyZWQgYnkgdGhlIFJhZGVnYXN0IEFQSS4KClByZXJlcXVpc2l0ZXMKLS0tLS0tLS0tLS0tLQotIFB5dGhvbiAzLjcrCi0gVGhlIGVudmlyb25tZW50IHZhcmlhYmxlIFJBREVHQVNUX0tFWSBtdXN0IGJlIHNldCB0byB5b3VyIFJhZGVnYXN0IEFQSSBrZXkKICBiZWZvcmUgcnVubmluZyB0aGlzIHNjcmlwdC4KCiAgU2V0dGluZyBSQURFR0FTVF9LRVkKICB+fn5+fn5+fn5+fn5+fn5+fn5+fgogIFdpbmRvd3MgKFBvd2VyU2hlbGwg4oCUIGN1cnJlbnQgc2Vzc2lvbiBvbmx5KToKICAgICAgJGVudjpSQURFR0FTVF9LRVkgPSAicmdfLi4uIgoKICBXaW5kb3dzIChwZXJzaXN0IGFjcm9zcyBzZXNzaW9ucyk6CiAgICAgIHNldHggUkFERUdBU1RfS0VZICJyZ18uLi4iCiAgICAgICMgT3BlbiBhIG5ldyB0ZXJtaW5hbCBhZnRlciBydW5uaW5nIHNldHggZm9yIHRoZSB2YWx1ZSB0byB0YWtlIGVmZmVjdC4KCiAgTGludXggLyBtYWNPUyAoY3VycmVudCBzZXNzaW9uIG9ubHkpOgogICAgICBleHBvcnQgUkFERUdBU1RfS0VZPSJyZ18uLi4iCgogIExpbnV4IC8gbWFjT1MgKHBlcnNpc3QgYWNyb3NzIHNlc3Npb25zIOKAlCBhZGQgdG8gc2hlbGwgcHJvZmlsZSk6CiAgICAgIGVjaG8gJ2V4cG9ydCBSQURFR0FTVF9LRVk9InJnXy4uLiInID4+IH4vLmJhc2hyYyAgICMgYmFzaAogICAgICBlY2hvICdleHBvcnQgUkFERUdBU1RfS0VZPSJyZ18uLi4iJyA+PiB+Ly56c2hyYyAgICAjIHpzaAogICAgICBzb3VyY2Ugfi8uYmFzaHJjICAgIyByZWxvYWQgd2l0aG91dCByZXN0YXJ0aW5nIHRoZSB0ZXJtaW5hbAoKICBOb3RlOiBQeXRob24ncyBvcy5lbnZpcm9uIHJlYWRzIHRoZSBwcm9jZXNzIGVudmlyb25tZW50IG9uIGJvdGggV2luZG93cyBhbmQKICBMaW51eCwgc28gdGhlIHNhbWUgc2NyaXB0IHdvcmtzIHVuY2hhbmdlZCBvbiBlaXRoZXIgcGxhdGZvcm0uCgpVc2FnZQotLS0tLQogICAgcHl0aG9uIGluc3RhbGxfcmFkZWdhc3QucHkKCldoYXQgdGhpcyBzY3JpcHQgZG9lcwotLS0tLS0tLS0tLS0tLS0tLS0tLS0KMS4gUmVhZHMgUkFERUdBU1RfS0VZIGZyb20gdGhlIGVudmlyb25tZW50IGFuZCBleGl0cyB3aXRoIGEgY2xlYXIgZXJyb3IgaWYgaXQKICAgaXMgbWlzc2luZy4KMi4gQ2FsbHMgdGhlIFJhZGVnYXN0IEFQSSB0byByZWdpc3RlciB0aGlzIGRldmljZSBhbmQgb2J0YWluIGEgUkFERUdBU1RfVE9LRU4uCjMuIFBlcnNpc3RzIFJBREVHQVNUX1RPS0VOIGZvciB0aGUgY3VycmVudCB1c2VyOgogICAgIC0gV2luZG93czogdmlhIHNldHgKICAgICAtIExpbnV4L21hY09TOiBhcHBlbmRlZCB0byB+Ly5iYXNocmMgaWYgbm90IGFscmVhZHkgcHJlc2VudAo0LiBEb3dubG9hZHMgdGhlIHBsYXRmb3JtLXNwZWNpZmljIGluc3RhbGwgc2NyaXB0IGZyb20gdGhlIFJhZGVnYXN0IEFQSSBhbmQKICAgZXhlY3V0ZXMgaXQgKGEgLmJhdCBmaWxlIG9uIFdpbmRvd3MsIGEgc2hlbGwgc2NyaXB0IHZpYSBzdWRvIG9uIExpbnV4KS4KIiIiCgppbXBvcnQgb3MKaW1wb3J0IHBsYXRmb3JtCmltcG9ydCBzdWJwcm9jZXNzCmltcG9ydCBzeXMKCnRyeToKICAgIGltcG9ydCByZXF1ZXN0cwpleGNlcHQgSW1wb3J0RXJyb3I6CiAgICBwcmludCgiSW5zdGFsbGluZyByZXF1aXJlZCBkZXBlbmRlbmN5OiByZXF1ZXN0cy4uLiIpCiAgICBzdWJwcm9jZXNzLnJ1bihbInV2IiwgImFkZCIsICJyZXF1ZXN0cyJdLCBjaGVjaz1UcnVlKQogICAgaW1wb3J0IHJlcXVlc3RzCgoKIyAtLS0tLS0tLS0tLS0tLS0tLS0tLS0tLS0tLS0tLS0tLS0tLS0tLS0tLS0tLS0tLS0tLS0tLS0tLS0tLS0tLS0tLS0tLS0tLS0tLS0KIyAxLiBSZWFkIGFuZCB2YWxpZGF0ZSB0aGUgQVBJIGtleSBmcm9tIHRoZSBlbnZpcm9ubWVudAojICAgIG9zLmVudmlyb24uZ2V0KCkgd29ya3MgaWRlbnRpY2FsbHkgb24gV2luZG93cyBhbmQgTGludXgvbWFjT1MuCiMgICAgT24gV2luZG93cywgZW52aXJvbm1lbnQgdmFyaWFibGUgbmFtZXMgYXJlIGNhc2UtaW5zZW5zaXRpdmUsIGJ1dCB1c2luZwojICAgIHRoZSBleGFjdCBuYW1lICJSQURFR0FTVF9LRVkiIGVuc3VyZXMgY29tcGF0aWJpbGl0eSBvbiBhbGwgcGxhdGZvcm1zLgojIC0tLS0tLS0tLS0tLS0tLS0tLS0tLS0tLS0tLS0tLS0tLS0tLS0tLS0tLS0tLS0tLS0tLS0tLS0tLS0tLS0tLS0tLS0tLS0tLS0tLQoKYXBpX2tleSA9IG9zLmVudmlyb24uZ2V0KCJSQURFR0FTVF9LRVkiKQppZiBub3QgYXBpX2tleToKICAgIHByaW50KAogICAgICAgICJFcnJvcjogUkFERUdBU1RfS0VZIGVudmlyb25tZW50IHZhcmlhYmxlIGlzIG5vdCBzZXQuXG4iCiAgICAgICAgIlxuIgogICAgICAgICJXaW5kb3dzIChQb3dlclNoZWxsKTpcbiIKICAgICAgICAnICAgICRlbnY6UkFERUdBU1RfS0VZID0gInJnXy4uLiJcbicKICAgICAgICAiICAgICMgb3IgdG8gcGVyc2lzdDogc2V0eCBSQURFR0FTVF9LRVkgXCJyZ18uLi5cIlxuIgogICAgICAgICJcbiIKICAgICAgICAiTGludXggLyBtYWNPUzpcbiIKICAgICAgICAnICAgIGV4cG9ydCBSQURFR0FTVF9LRVk9InJnXy4uLiJcbicKICAgICAgICAiICAgICMgb3IgYWRkIHRoZSBsaW5lIGFib3ZlIHRvIH4vLmJhc2hyYyAvIH4vLnpzaHJjIGZvciBwZXJzaXN0ZW5jZSIKICAgICkKICAgIHN5cy5leGl0KDEpCgoKIyAtLS0tLS0tLS0tLS0tLS0tLS0tLS0tLS0tLS0tLS0tLS0tLS0tLS0tLS0tLS0tLS0tLS0tLS0tLS0tLS0tLS0tLS0tLS0tLS0tLS0KIyAyLiBSZWdpc3RlciB0aGlzIGRldmljZSBhbmQgb2J0YWluIHRoZSBkZXZpY2UgdG9rZW4KIyAtLS0tLS0tLS0tLS0tLS0tLS0tLS0tLS0tLS0tLS0tLS0tLS0tLS0tLS0tLS0tLS0tLS0tLS0tLS0tLS0tLS0tLS0tLS0tLS0tLS0KCnByaW50KCJSZWdpc3RlcmluZyBkZXZpY2Ugd2l0aCBSYWRlZ2FzdCBBUEkuLi4iKQpyZXNwb25zZSA9IHJlcXVlc3RzLnBvc3QoCiAgICAiaHR0cHM6Ly9jb25zb2xlLWFwaS5yYWRlZ2FzdC5hcHAvYXBpL3YxL2RldmljZXMvIiwKICAgIGhlYWRlcnM9ewogICAgICAgICJhY2NlcHQiOiAiYXBwbGljYXRpb24vanNvbiIsCiAgICAgICAgIlgtQVBJLUtleSI6IGFwaV9rZXksCiAgICAgICAgIkF1dGhvcml6YXRpb24iOiBhcGlfa2V5LAogICAgICAgICJDb250ZW50LVR5cGUiOiAiYXBwbGljYXRpb24vanNvbiIsCiAgICB9LAogICAganNvbj17CiAgICAgICAgIm5hbWUiOiAic3RyaW5nIiwKICAgICAgICAiZ3JvdXBfaWQiOiAxMCwKICAgIH0sCikKcmVzcG9uc2UucmFpc2VfZm9yX3N0YXR1cygpCgpkZXZpY2UgPSByZXNwb25zZS5qc29uKCkKcHJpbnQoZiJEZXZpY2UgcmVnaXN0ZXJlZDoge2RldmljZX0iKQoKcmFkZWdhc3RfdG9rZW4gPSBkZXZpY2VbInRva2VuIl0KcHJpbnQoZiJSQURFR0FTVF9UT0tFTjoge3JhZGVnYXN0X3Rva2VufSIpCgoKIyAtLS0tLS0tLS0tLS0tLS0tLS0tLS0tLS0tLS0tLS0tLS0tLS0tLS0tLS0tLS0tLS0tLS0tLS0tLS0tLS0tLS0tLS0tLS0tLS0tLS0KIyAzLiBQZXJzaXN0IFJBREVHQVNUX1RPS0VOIGFuZCBydW4gdGhlIHBsYXRmb3JtLXNwZWNpZmljIGluc3RhbGwgc2NyaXB0CiMgLS0tLS0tLS0tLS0tLS0tLS0tLS0tLS0tLS0tLS0tLS0tLS0tLS0tLS0tLS0tLS0tLS0tLS0tLS0tLS0tLS0tLS0tLS0tLS0tLS0tCgpjdXJyZW50X29zID0gcGxhdGZvcm0uc3lzdGVtKCkKCmlmIGN1cnJlbnRfb3MgPT0gIldpbmRvd3MiOgogICAgIyBQZXJzaXN0IHRoZSB0b2tlbiBmb3IgdGhlIGN1cnJlbnQgdXNlciBhY3Jvc3Mgc2Vzc2lvbnMKICAgIHN1YnByb2Nlc3MucnVuKFsic2V0eCIsICJSQURFR0FTVF9UT0tFTiIsIHJhZGVnYXN0X3Rva2VuXSwgY2hlY2s9VHJ1ZSkKICAgIG9zLmVudmlyb25bIlJBREVHQVNUX1RPS0VOIl0gPSByYWRlZ2FzdF90b2tlbgoKICAgIHByaW50KCJGZXRjaGluZyBXaW5kb3dzIGluc3RhbGwgc2NyaXB0Li4uIikKICAgIGluc3RhbGxfcmVzcG9uc2UgPSByZXF1ZXN0cy5nZXQoCiAgICAgICAgImh0dHBzOi8vY29uc29sZS1hcGkucmFkZWdhc3QuYXBwL2FwaS92MS9kZXZpY2UvaW5zdGFsbCIsCiAgICAgICAgcGFyYW1zPXsib3MiOiAid2luZG93cyJ9LAogICAgICAgIGhlYWRlcnM9eyJhY2NlcHQiOiAiYXBwbGljYXRpb24vanNvbiJ9LAogICAgKQogICAgaW5zdGFsbF9yZXNwb25zZS5yYWlzZV9mb3Jfc3RhdHVzKCkKICAgIGluc3RhbGxfc2NyaXB0ID0gaW5zdGFsbF9yZXNwb25zZS50ZXh0CgogICAgYmF0X3BhdGggPSBvcy5wYXRoLmpvaW4ob3MucGF0aC5kaXJuYW1lKG9zLnBhdGguYWJzcGF0aChfX2ZpbGVfXykpLCAicmFkZWdhc3RfaW5zdGFsbC5iYXQiKQogICAgd2l0aCBvcGVuKGJhdF9wYXRoLCAidyIpIGFzIGY6CiAgICAgICAgZi53cml0ZShpbnN0YWxsX3NjcmlwdCkKICAgIHByaW50KGYiSW5zdGFsbCBzY3JpcHQgc2F2ZWQgdG8ge2JhdF9wYXRofSIpCiAgICBwcmludCgiUnVubmluZyBXaW5kb3dzIGluc3RhbGwgc2NyaXB0Li4uIikKICAgIHN1YnByb2Nlc3MucnVuKFtiYXRfcGF0aF0sIGNoZWNrPVRydWUpCgplbHNlOgogICAgcHJpbnQoIkZldGNoaW5nIExpbnV4IGluc3RhbGwgc2NyaXB0Li4uIikKICAgIGluc3RhbGxfcmVzcG9uc2UgPSByZXF1ZXN0cy5nZXQoCiAgICAgICAgImh0dHBzOi8vY29uc29sZS1hcGkucmFkZWdhc3QuYXBwL2FwaS92MS9kZXZpY2UvaW5zdGFsbCIsCiAgICAgICAgcGFyYW1zPXsib3MiOiAibGludXgifSwKICAgICAgICBoZWFkZXJzPXsiYWNjZXB0IjogImFwcGxpY2F0aW9uL2pzb24ifSwKICAgICkKICAgIGluc3RhbGxfcmVzcG9uc2UucmFpc2VfZm9yX3N0YXR1cygpCiAgICBpbnN0YWxsX3NjcmlwdCA9IGluc3RhbGxfcmVzcG9uc2UudGV4dAoKICAgICMgUGVyc2lzdCB0aGUgdG9rZW4gZm9yIHRoZSBjdXJyZW50IHVzZXIgYWNyb3NzIHNlc3Npb25zCiAgICBzaGVsbF9yYyA9IG9zLnBhdGguZXhwYW5kdXNlcigifi8uYmFzaHJjIikKICAgIGV4cG9ydF9saW5lID0gZidcbmV4cG9ydCBSQURFR0FTVF9UT0tFTj0ie3JhZGVnYXN0X3Rva2VufSJcbicKICAgIHdpdGggb3BlbihzaGVsbF9yYywgInIiKSBhcyBmOgogICAgICAgIGNvbnRlbnRzID0gZi5yZWFkKCkKICAgIGlmICJSQURFR0FTVF9UT0tFTiIgbm90IGluIGNvbnRlbnRzOgogICAgICAgIHdpdGggb3Blbihz" > "%SB%"
echo Decoding script: 1/2 (50%)
echo|set /p="aGVsbF9yYywgImEiKSBhcyBmOgogICAgICAgICAgICBmLndyaXRlKGV4cG9ydF9saW5lKQogICAgICAgIHByaW50KGYiUkFERUdBU1RfVE9LRU4gd3JpdHRlbiB0byB7c2hlbGxfcmN9IOKAlCByZXN0YXJ0IHlvdXIgc2hlbGwgb3IgcnVuOiBzb3VyY2Ugfi8uYmFzaHJjIikKCiAgICBwcmludCgiUnVubmluZyBMaW51eCBpbnN0YWxsIHNjcmlwdC4uLiIpCiAgICBzdWJwcm9jZXNzLnJ1bigKICAgICAgICBbInN1ZG8iLCBmIlJBREVHQVNUX1RPS0VOPXtyYWRlZ2FzdF90b2tlbn0iLCAic2giXSwKICAgICAgICBpbnB1dD1pbnN0YWxsX3NjcmlwdCwKICAgICAgICB0ZXh0PVRydWUsCiAgICAgICAgY2hlY2s9VHJ1ZSwKICAgICkK" >> "%SB%"
echo Decoding script: 2/2 (100%)
powershell -Command "$b = Get-Content -Path $env:SB -Raw; $x = [System.Convert]::FromBase64String($b); [System.IO.File]::WriteAllBytes($env:SO, $x)"

echo.

echo Running installation script with uv...
rem Executing using uv run
uv run --python=%PYTHON_VERSION% "%INSTALL_SCRIPT%"

if errorlevel 1 (
    echo ERROR: Installation script failed with error code %ERRORLEVEL%
) else (
    echo.
    echo Installation completed successfully!
)
echo.
del "%INSTALL_SCRIPT%" 2>nul
del "%INSTALL_B64%" 2>nul
PAUSE
